#!/usr/bin/env bash
set -euo pipefail
cd /workspace/hopper_runtime
export BEAM_WEIGHT_DIR=${1:?artifact directory required}
export BEAM_HOPPER_NATIVE_FP8=1 BEAM_STREAM1_TRANSFORMER_GRAPH_BENCH=1
export BEAM_STREAM1_TRANSFORMER_FINAL_CLS_ONLY=1 BEAM_STREAM1_TRANSFORMER_FINAL_CLS_ATTENTION=1
export BEAM_STREAM1_TRANSFORMER_FINAL_CLS_SPLIT_QKV=1 BEAM_STREAM1_TRANSFORMER_FUSED_INPUT_LAYERNORM=1
export BEAM_STREAM1_TRANSFORMER_HOPPER_QKV=fp16_tma BEAM_STREAM1_TRANSFORMER_HOPPER_FF1=fp16_tma
export BEAM_STREAM1_TRANSFORMER_FF2_POLICY=m128n128 BEAM_STREAM1_TRANSFORMER_COMPACT57=1
export BEAM_STREAM1_TRANSFORMER_B_MICRO=128 BEAM_STREAM1_TRANSFORMER_CONCURRENCY=1
export BEAM_STREAM1_TRANSFORMER_DUAL_INPUT_LN=0 BEAM_STREAM1_TRANSFORMER_HOPPER_FF1_EPILOGUE=128x64
export BEAM_STREAM1_TRANSFORMER_BENCH_ITERS=2
export LD_LIBRARY_PATH=/venv/main/lib/python3.12/site-packages/nvidia/nccl/lib:/usr/local/cuda/lib64
exec compute-sanitizer --tool "${H200_SANITIZER_TOOL:-memcheck}" --error-exitcode 2 "${H200_BUILD_DIR:-/workspace/build}/stream_benchmark" 1000
