#!/usr/bin/env bash
set -euo pipefail
cd /workspace/MGBFS
unset BEAM_STREAM1_TRANSFORMER_HOPPER_QKV BEAM_STREAM1_TRANSFORMER_HOPPER_FF1
unset BEAM_STREAM1_TRANSFORMER_FF2_POLICY BEAM_STREAM1_TRANSFORMER_FUSED_INPUT_LAYERNORM
export BEAM_WEIGHT_DIR=/workspace BEAM_STREAM1_SYNTHETIC_STATES=1
export BEAM_STREAM1_TRANSFORMER_GRAPH_BENCH=1 BEAM_STREAM1_TRANSFORMER_BENCH_ITERS=100
export BEAM_STREAM1_TRANSFORMER_COMPACT57=1
export BEAM_STREAM1_TRANSFORMER_CONCURRENCY=1
export BEAM_STREAM1_TRANSFORMER_FINAL_CLS_ONLY=0
export BEAM_STREAM1_TRANSFORMER_FINAL_CLS_ATTENTION=0
export BEAM_STREAM1_TRANSFORMER_FINAL_CLS_SPLIT_QKV=0
for micro in 128 256 384 512 768 1024 2048 4096; do
  for rep in 1 2 3; do
    tag=compare_native_full_m${micro}_c1_${rep}
    BEAM_STREAM1_TRANSFORMER_B_MICRO=$micro \
      BEAM_STREAM_BENCH_REPORT=/workspace/results/${tag}.md \
      BEAM_STREAM1_TRANSFORMER_SCORE_DUMP=/workspace/results/${tag}.bin \
      /workspace/build/stream_benchmark 1000 > /workspace/results/${tag}.log 2>&1
  done
done

export BEAM_STREAM1_TRANSFORMER_FINAL_CLS_ONLY=1
export BEAM_STREAM1_TRANSFORMER_FINAL_CLS_ATTENTION=1
export BEAM_STREAM1_TRANSFORMER_FINAL_CLS_SPLIT_QKV=1
export BEAM_STREAM1_TRANSFORMER_FUSED_INPUT_LAYERNORM=1
export BEAM_STREAM1_TRANSFORMER_HOPPER_QKV=fp16_tma
export BEAM_STREAM1_TRANSFORMER_HOPPER_FF1=fp16_tma
export BEAM_STREAM1_TRANSFORMER_FF2_POLICY=m128n128
for lanes in 1 8; do
  for rep in 1 2 3; do
    tag=compare_native_optimized_m384_c${lanes}_${rep}
    BEAM_STREAM1_TRANSFORMER_B_MICRO=384 BEAM_STREAM1_TRANSFORMER_CONCURRENCY=$lanes \
      BEAM_STREAM_BENCH_REPORT=/workspace/results/${tag}.md \
      BEAM_STREAM1_TRANSFORMER_SCORE_DUMP=/workspace/results/${tag}.bin \
      /workspace/build/stream_benchmark 1000 > /workspace/results/${tag}.log 2>&1
  done
done
