#!/usr/bin/env bash
set -euo pipefail
cd /workspace/MGBFS
export BEAM_WEIGHT_DIR=${BEAM_WEIGHT_DIR:-/workspace}
export BEAM_GENERATOR_PATH=/workspace/puzzle_info.json
export BEAM_PUZZLE_INFO_JSON=/workspace/puzzle_info.json
export BEAM_TEST_CSV=/workspace/test.csv
export BEAM_STREAM1_TRANSFORMER_HOPPER=off
export BEAM_STREAM1_TRANSFORMER_FINAL_CLS_ONLY=1
export BEAM_STREAM1_TRANSFORMER_FINAL_CLS_ATTENTION=1
export BEAM_STREAM1_TRANSFORMER_FINAL_CLS_SPLIT_QKV=1
export BEAM_STREAM1_TRANSFORMER_FUSED_INPUT_LAYERNORM=1
export BEAM_STREAM1_EXECUTOR=native_cuda_graph
export BEAM_RUNTIME_CONFIG_MODE=manual
export BEAM_B_MICRO=${BEAM_B_MICRO:-192}
export BEAM_STREAM1_CONCURRENCY=${BEAM_STREAM1_CONCURRENCY:-12}
export BEAM_STREAM3_RING_SLOTS=${BEAM_STREAM3_RING_SLOTS:-12}
export BEAM_RING_GRAPH_EXECS_PER_LANE=32
export BEAM_SHARD_COUNT=${BEAM_SHARD_COUNT:-32}
export BEAM_STREAM4_BATCH_ALIGNMENT=1024
export BEAM_STREAM4_BATCH_CANDIDATES=524288
export BEAM_STREAM4_TRIGGER_CANDIDATES=1048576
export BEAM_STREAM4_ACTIVE_SORT_SLOTS=4
export BEAM_SHARD_BUFFER_COUNT=2
export BEAM_SHARD_CAPACITY_SCALE_PPM=1000000
beam=${BEAM_WIDTH:-100000000}
export BEAM_SHARD_CAPACITY_CANDIDATES=$(( ((beam + BEAM_SHARD_COUNT*1024 - 1)/(BEAM_SHARD_COUNT*1024))*1024 ))
export BEAM_FINAL_MATERIALIZE_CHUNK_CANDIDATES=65536
export BEAM_FINAL_MATERIALIZE_EXCHANGE_SCALE_PPM=1000000
export BEAM_GPU_HEADROOM_BYTES=4294967296
export BEAM_HISTORY_MODE=static_hybrid
export BEAM_HISTORY_RAM_BYTES=34359738368
export BEAM_HISTORY_DISK_BYTES=68719476736
export BEAM_SOLVED_NEIGHBORHOOD_RADIUS=4
export BEAM_SOLVED_NEIGHBORHOOD_MAX_ENTRIES=3000000
export BEAM_ENABLE_DEBUG=1 BEAM_DEPTH_LOG_EVERY=1
export WORLD_SIZE=1 RANK=0 LOCAL_RANK=0
mkdir -p /workspace/results
exec /workspace/build/production_runner "${PUZZLE_ID:-1000}" "${DEPTH_LIMIT:-9}" "$beam"
