#pragma once

#include "types.hpp"

#include <cstddef>

namespace beam {

constexpr std::uint32_t STREAM_FATAL_TRACE_WORDS = 26;
constexpr std::uint32_t STREAM_FATAL_STREAM3_SPILL_OVERFLOW = 3001;
constexpr std::uint32_t STREAM_FATAL_STREAM3_DOUBLE_BUFFER_OVERFLOW = 3002;

enum StreamFatalTraceSlot : std::uint32_t {
    FatalTraceCode = 0,
    FatalTraceShard = 1,
    FatalTraceGroup = 2,
    FatalTraceExisting = 3,
    FatalTraceAvailable = 4,
    FatalTraceRawCount = 5,
    FatalTraceWriteCount = 6,
    FatalTraceSpillCount = 7,
    FatalTraceSpillOffset = 8,
    FatalTraceSpillEnd = 9,
    FatalTraceSpillCapacity = 10,
    FatalTraceCleanCount = 11,
    FatalTraceDirtyCount = 12,
    FatalTraceProcessingFlag = 13,
    FatalTraceShardCapacity = 14,
    FatalTraceStream4Batch = 15,
    FatalTraceAppendToActiveSpill = 16,
    FatalTraceLogicalShard = 17,
    FatalTraceSelectedBuffer = 18,
    FatalTraceSiblingShard = 19,
    FatalTraceSiblingExisting = 20,
    FatalTraceSiblingAvailable = 21,
    FatalTraceSiblingCleanCount = 22,
    FatalTraceSiblingDirtyCount = 23,
    FatalTraceSiblingProcessingFlag = 24,
    FatalTraceShardBufferCount = 25
};

void stream3_pack_threshold_cuda(
    const std::uint32_t* score_ring,
    const Hash128* hash_ring,
    const std::uint64_t* parent_base,
    const std::uint32_t* count,
    Hash128* compact_key,
    std::uint64_t* compact_val,
    Hash128* reduce_key_scratch,
    std::uint64_t* reduce_val_scratch,
    Hash128* unique_key,
    std::uint64_t* unique_val,
    std::uint32_t* keep_flags,
    std::uint32_t* block_counts,
    std::uint32_t* block_offsets,
    std::uint32_t* unique_count,
    void* cub_temp_storage,
    std::size_t cub_temp_storage_bytes,
    std::uint32_t current_threshold,
    std::uint32_t b_micro,
    std::uint32_t stream3_batch_candidates,
    cudaStream_t stream);

void stream3_pack_threshold_device_threshold_cuda(
    const std::uint32_t* score_ring,
    const Hash128* hash_ring,
    const std::uint64_t* parent_base,
    const std::uint32_t* count,
    Hash128* compact_key,
    std::uint64_t* compact_val,
    Hash128* reduce_key_scratch,
    std::uint64_t* reduce_val_scratch,
    Hash128* unique_key,
    std::uint64_t* unique_val,
    std::uint32_t* keep_flags,
    std::uint32_t* block_counts,
    std::uint32_t* block_offsets,
    std::uint32_t* unique_count,
    void* cub_temp_storage,
    std::size_t cub_temp_storage_bytes,
    const std::uint32_t* current_threshold,
    std::uint32_t b_micro,
    std::uint32_t stream3_batch_candidates,
    cudaStream_t stream);

void stream3_restore_owner_split_cuda(
    const Hash128* unique_key,
    const std::uint64_t* unique_val,
    const std::uint32_t* unique_count,
    const std::uint64_t* parent_base,
    CandidateMeta* local_pending_buffer,
    std::uint32_t* local_pending_count,
    CandidateMeta* remote_send_buffer,
    std::uint32_t* send_count,
    std::uint32_t* send_offset,
    std::uint32_t* owner_scratch,
    std::uint16_t local_rank,
    std::uint32_t world_size,
    std::uint32_t b_micro,
    std::uint32_t max_candidates,
    cudaStream_t stream);

void stream3_collect_local_pending_cuda(
    const CandidateMeta* local_pending_buffer,
    const std::uint32_t* local_pending_count,
    CandidateMeta* survivor_shard,
    std::uint32_t* clean_count,
    std::uint32_t* dirty_count,
    const std::uint32_t* processing_flag,
    CandidateMeta* global_spill_buffer_a,
    CandidateMeta* global_spill_buffer_b,
    std::uint32_t* global_spill_count,
    std::uint32_t* global_spill_active_index,
    std::uint32_t* write_buffer_index,
    std::uint32_t* shard_counts,
    std::uint32_t* shard_offsets,
    std::uint32_t* spill_counts,
    std::uint32_t* spill_offsets,
    std::uint32_t* partition_key_a,
    std::uint32_t* partition_key_b,
    CandidateMeta* partition_val_a,
    CandidateMeta* partition_val_b,
    std::uint32_t* partition_unique_shard,
    std::uint32_t* partition_unique_counts,
    std::uint32_t* partition_unique_count,
    void* cub_temp_storage,
    std::size_t cub_temp_storage_bytes,
    std::uint32_t max_candidates,
    std::uint32_t shard_count,
    std::uint32_t shard_buffer_count,
    std::uint32_t shard_capacity_candidates,
    std::uint32_t stream4_batch_candidates,
    std::uint32_t global_spill_capacity,
    cudaStream_t stream,
    std::uint32_t* fatal_error_flag = nullptr,
    std::uint64_t* fatal_error_trace = nullptr);

void stream3_restore_collect_single_owner_cuda(
    const Hash128* unique_key,
    const std::uint64_t* unique_val,
    const std::uint32_t* unique_count,
    const std::uint64_t* parent_base,
    std::uint32_t* local_pending_count,
    std::uint32_t* send_count,
    std::uint32_t* send_offset,
    CandidateMeta* survivor_shard,
    std::uint32_t* clean_count,
    std::uint32_t* dirty_count,
    const std::uint32_t* processing_flag,
    CandidateMeta* global_spill_buffer_a,
    CandidateMeta* global_spill_buffer_b,
    std::uint32_t* global_spill_count,
    std::uint32_t* global_spill_active_index,
    std::uint32_t* write_buffer_index,
    std::uint32_t* shard_counts,
    std::uint32_t* shard_offsets,
    std::uint32_t* spill_counts,
    std::uint32_t* spill_offsets,
    std::uint32_t* partition_key_a,
    std::uint32_t* partition_key_b,
    CandidateMeta* partition_val_a,
    CandidateMeta* partition_val_b,
    std::uint32_t* partition_unique_shard,
    std::uint32_t* partition_unique_counts,
    std::uint32_t* partition_unique_count,
    void* cub_temp_storage,
    std::size_t cub_temp_storage_bytes,
    std::uint16_t local_rank,
    std::uint32_t b_micro,
    std::uint32_t max_candidates,
    std::uint32_t shard_count,
    std::uint32_t shard_buffer_count,
    std::uint32_t shard_capacity_candidates,
    std::uint32_t stream4_batch_candidates,
    std::uint32_t global_spill_capacity,
    cudaStream_t stream,
    std::uint32_t* fatal_error_flag = nullptr,
    std::uint64_t* fatal_error_trace = nullptr);

void stream3_drain_global_spill_cuda(
    CandidateMeta* global_spill_buffer_a,
    CandidateMeta* global_spill_buffer_b,
    std::uint32_t* global_spill_count,
    std::uint32_t* global_spill_active_index,
    CandidateMeta* survivor_shard,
    std::uint32_t* clean_count,
    std::uint32_t* dirty_count,
    const std::uint32_t* processing_flag,
    std::uint32_t* shard_counts,
    std::uint32_t* shard_offsets,
    std::uint32_t* spill_counts,
    std::uint32_t* spill_offsets,
    std::uint32_t* partition_key_a,
    std::uint32_t* partition_key_b,
    CandidateMeta* partition_val_a,
    CandidateMeta* partition_val_b,
    std::uint32_t* partition_unique_shard,
    std::uint32_t* partition_unique_counts,
    std::uint32_t* partition_unique_count,
    void* cub_temp_storage,
    std::size_t cub_temp_storage_bytes,
    std::uint32_t shard_count,
    std::uint32_t global_spill_capacity,
    std::uint32_t shard_capacity_candidates,
    std::uint32_t stream4_batch_candidates,
    cudaStream_t stream,
    std::uint32_t* fatal_error_flag = nullptr,
    std::uint64_t* fatal_error_trace = nullptr);

void stream3_collect_remote_recv_cuda(
    const CandidateMeta* remote_recv_buffer,
    const std::uint32_t* recv_count,
    const std::uint32_t* recv_offset,
    CandidateMeta* survivor_shard,
    std::uint32_t* clean_count,
    std::uint32_t* dirty_count,
    const std::uint32_t* processing_flag,
    CandidateMeta* global_spill_buffer_a,
    CandidateMeta* global_spill_buffer_b,
    std::uint32_t* global_spill_count,
    std::uint32_t* global_spill_active_index,
    std::uint32_t* write_buffer_index,
    std::uint32_t* shard_counts,
    std::uint32_t* shard_offsets,
    std::uint32_t* spill_counts,
    std::uint32_t* spill_offsets,
    std::uint32_t* partition_key_a,
    std::uint32_t* partition_key_b,
    CandidateMeta* partition_val_a,
    CandidateMeta* partition_val_b,
    std::uint32_t* partition_unique_shard,
    std::uint32_t* partition_unique_counts,
    std::uint32_t* partition_unique_count,
    void* cub_temp_storage,
    std::size_t cub_temp_storage_bytes,
    std::uint32_t max_candidates,
    std::uint32_t world_size,
    std::uint32_t shard_count,
    std::uint32_t shard_buffer_count,
    std::uint32_t shard_capacity_candidates,
    std::uint32_t stream4_batch_candidates,
    std::uint32_t global_spill_capacity,
    cudaStream_t stream,
    std::uint32_t* fatal_error_flag = nullptr,
    std::uint64_t* fatal_error_trace = nullptr);

void stream3_build_ready_shard_queue_cuda(
    const std::uint32_t* clean_count,
    const std::uint32_t* dirty_count,
    std::uint32_t* processing_flag,
    std::uint32_t* write_buffer_index,
    std::uint32_t* ready_flag,
    std::uint32_t* ready_shard_list,
    std::uint32_t* ready_count,
    std::uint32_t shard_count,
    std::uint32_t shard_buffer_count,
    std::uint32_t shard_capacity_candidates,
    std::uint32_t stream3_batch_candidates,
    std::uint32_t stream4_trigger_candidates,
    bool force_dirty_flush,
    bool force_clean_flush,
    cudaStream_t stream);

} // namespace beam
