function(beam_configure_state_sizing)
    set(BEAM_PUZZLE_INFO_JSON "${CMAKE_SOURCE_DIR}/data/puzzle_info.json" CACHE FILEPATH "Puzzle info JSON used to infer state length")
    set(BEAM_STATE_LOGICAL_BYTES "" CACHE STRING "Logical puzzle state bytes/elements; empty means infer from puzzle_info.json")
    set(BEAM_STATE_ALIGNMENT "16" CACHE STRING "Physical state storage alignment in bytes")
    set(BEAM_MOVE_COUNT "" CACHE STRING "Puzzle move/generator count; empty means infer from puzzle_info.json")

    if(NOT BEAM_STATE_LOGICAL_BYTES)
        if(NOT EXISTS "${BEAM_PUZZLE_INFO_JSON}")
            message(FATAL_ERROR "BEAM_STATE_LOGICAL_BYTES is empty and BEAM_PUZZLE_INFO_JSON does not exist: ${BEAM_PUZZLE_INFO_JSON}")
        endif()
        file(READ "${BEAM_PUZZLE_INFO_JSON}" BEAM_PUZZLE_INFO_TEXT)
        string(REGEX MATCH "\"central_state\"[ \t\r\n]*:[ \t\r\n]*\\[[^]]*\\]" BEAM_CENTRAL_STATE_MATCH "${BEAM_PUZZLE_INFO_TEXT}")
        if(NOT BEAM_CENTRAL_STATE_MATCH)
            message(FATAL_ERROR "Cannot infer BEAM_STATE_LOGICAL_BYTES: central_state array not found in ${BEAM_PUZZLE_INFO_JSON}")
        endif()
        string(REGEX REPLACE ".*\\[([^]]*)\\].*" "\\1" BEAM_CENTRAL_STATE_VALUES "${BEAM_CENTRAL_STATE_MATCH}")
        string(REGEX REPLACE "[ \t\r\n]" "" BEAM_CENTRAL_STATE_VALUES "${BEAM_CENTRAL_STATE_VALUES}")
        if("${BEAM_CENTRAL_STATE_VALUES}" STREQUAL "")
            message(FATAL_ERROR "Cannot infer BEAM_STATE_LOGICAL_BYTES: central_state array is empty")
        endif()
        string(REGEX REPLACE "[^,]" "" BEAM_CENTRAL_STATE_COMMAS "${BEAM_CENTRAL_STATE_VALUES}")
        string(LENGTH "${BEAM_CENTRAL_STATE_COMMAS}" BEAM_CENTRAL_STATE_COMMA_COUNT)
        math(EXPR BEAM_STATE_LOGICAL_BYTES "${BEAM_CENTRAL_STATE_COMMA_COUNT} + 1")
        set(BEAM_STATE_LOGICAL_BYTES "${BEAM_STATE_LOGICAL_BYTES}" CACHE STRING "Logical puzzle state bytes/elements; empty means infer from puzzle_info.json" FORCE)
    endif()

    if(NOT BEAM_MOVE_COUNT)
        if(NOT DEFINED BEAM_PUZZLE_INFO_TEXT)
            if(NOT EXISTS "${BEAM_PUZZLE_INFO_JSON}")
                message(FATAL_ERROR "BEAM_MOVE_COUNT is empty and BEAM_PUZZLE_INFO_JSON does not exist: ${BEAM_PUZZLE_INFO_JSON}")
            endif()
            file(READ "${BEAM_PUZZLE_INFO_JSON}" BEAM_PUZZLE_INFO_TEXT)
        endif()
        string(REGEX MATCH "\"generators\"[ \t\r\n]*:[ \t\r\n]*\\{" BEAM_GENERATORS_MATCH "${BEAM_PUZZLE_INFO_TEXT}")
        if(BEAM_GENERATORS_MATCH)
            string(FIND "${BEAM_PUZZLE_INFO_TEXT}" "\"generators\"" BEAM_GENERATORS_POS)
            string(SUBSTRING "${BEAM_PUZZLE_INFO_TEXT}" "${BEAM_GENERATORS_POS}" -1 BEAM_GENERATORS_TEXT)
            string(REGEX REPLACE "[^[]" "" BEAM_GENERATOR_ARRAY_MARKERS "${BEAM_GENERATORS_TEXT}")
            string(LENGTH "${BEAM_GENERATOR_ARRAY_MARKERS}" BEAM_MOVE_COUNT)
        else()
            string(FIND "${BEAM_PUZZLE_INFO_TEXT}" "\"actions\"" BEAM_ACTIONS_POS)
            if(BEAM_ACTIONS_POS GREATER_EQUAL 0)
                string(FIND "${BEAM_PUZZLE_INFO_TEXT}" "\"names\"" BEAM_NAMES_POS)
                if(BEAM_NAMES_POS LESS 0)
                    string(LENGTH "${BEAM_PUZZLE_INFO_TEXT}" BEAM_NAMES_POS)
                endif()
                math(EXPR BEAM_ACTIONS_LEN "${BEAM_NAMES_POS} - ${BEAM_ACTIONS_POS}")
                string(SUBSTRING "${BEAM_PUZZLE_INFO_TEXT}" "${BEAM_ACTIONS_POS}" "${BEAM_ACTIONS_LEN}" BEAM_ACTIONS_TEXT)
                string(REGEX REPLACE "[^[]" "" BEAM_ACTION_BRACKETS "${BEAM_ACTIONS_TEXT}")
                string(LENGTH "${BEAM_ACTION_BRACKETS}" BEAM_ACTION_BRACKET_COUNT)
                math(EXPR BEAM_MOVE_COUNT "${BEAM_ACTION_BRACKET_COUNT} - 1")
            else()
                string(REGEX MATCH "\"names\"[ \t\r\n]*:[ \t\r\n]*\\[[^]]*\\]" BEAM_GENERATOR_NAMES_MATCH "${BEAM_PUZZLE_INFO_TEXT}")
                if(NOT BEAM_GENERATOR_NAMES_MATCH)
                    message(FATAL_ERROR "Cannot infer BEAM_MOVE_COUNT: generators object, actions array, or names array not found in ${BEAM_PUZZLE_INFO_JSON}")
                endif()
                string(REGEX REPLACE ".*\\[([^]]*)\\].*" "\\1" BEAM_GENERATOR_NAME_VALUES "${BEAM_GENERATOR_NAMES_MATCH}")
                string(REGEX REPLACE "[ \t\r\n]" "" BEAM_GENERATOR_NAME_VALUES "${BEAM_GENERATOR_NAME_VALUES}")
                if("${BEAM_GENERATOR_NAME_VALUES}" STREQUAL "")
                    message(FATAL_ERROR "Cannot infer BEAM_MOVE_COUNT: names array is empty")
                endif()
                string(REGEX REPLACE "[^,]" "" BEAM_GENERATOR_NAME_COMMAS "${BEAM_GENERATOR_NAME_VALUES}")
                string(LENGTH "${BEAM_GENERATOR_NAME_COMMAS}" BEAM_GENERATOR_NAME_COMMA_COUNT)
                math(EXPR BEAM_MOVE_COUNT "${BEAM_GENERATOR_NAME_COMMA_COUNT} + 1")
            endif()
        endif()
        if(BEAM_MOVE_COUNT LESS 1)
            message(FATAL_ERROR "Cannot infer BEAM_MOVE_COUNT: no generators found in ${BEAM_PUZZLE_INFO_JSON}")
        endif()
        set(BEAM_MOVE_COUNT "${BEAM_MOVE_COUNT}" CACHE STRING "Puzzle move/generator count; empty means infer from puzzle_info.json" FORCE)
    endif()

    math(EXPR BEAM_STATE_PHYSICAL_BYTES "(((${BEAM_STATE_LOGICAL_BYTES} + ${BEAM_STATE_ALIGNMENT} - 1) / ${BEAM_STATE_ALIGNMENT}) * ${BEAM_STATE_ALIGNMENT})")
    math(EXPR BEAM_STATE_MIN_PHYSICAL_BYTES "${BEAM_STATE_LOGICAL_BYTES} + 4")
    if(BEAM_STATE_PHYSICAL_BYTES LESS BEAM_STATE_MIN_PHYSICAL_BYTES)
        math(EXPR BEAM_STATE_PHYSICAL_BYTES "(((${BEAM_STATE_LOGICAL_BYTES} + 4 + ${BEAM_STATE_ALIGNMENT} - 1) / ${BEAM_STATE_ALIGNMENT}) * ${BEAM_STATE_ALIGNMENT})")
    endif()

    set(BEAM_STATE_PHYSICAL_BYTES "${BEAM_STATE_PHYSICAL_BYTES}" CACHE STRING "Physical state storage bytes" FORCE)
    set(BEAM_STATE_LOGICAL_BYTES "${BEAM_STATE_LOGICAL_BYTES}" PARENT_SCOPE)
    set(BEAM_STATE_PHYSICAL_BYTES "${BEAM_STATE_PHYSICAL_BYTES}" PARENT_SCOPE)
    set(BEAM_STATE_ALIGNMENT "${BEAM_STATE_ALIGNMENT}" PARENT_SCOPE)
    set(BEAM_MOVE_COUNT "${BEAM_MOVE_COUNT}" PARENT_SCOPE)
endfunction()
